// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc1
// source: feed.proto

package feedRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullLatestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *PullLatestReq) Reset() {
	*x = PullLatestReq{}
	mi := &file_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullLatestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullLatestReq) ProtoMessage() {}

func (x *PullLatestReq) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullLatestReq.ProtoReflect.Descriptor instead.
func (*PullLatestReq) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

func (x *PullLatestReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PullLatestReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PullReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Limit     int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TimeStamp int64 `protobuf:"varint,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *PullReq) Reset() {
	*x = PullReq{}
	mi := &file_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullReq) ProtoMessage() {}

func (x *PullReq) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullReq.ProtoReflect.Descriptor instead.
func (*PullReq) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

func (x *PullReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PullReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PullReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type PullResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    []int64 `protobuf:"varint,1,rep,packed,name=userId,proto3" json:"userId,omitempty"`
	ContentId []int64 `protobuf:"varint,2,rep,packed,name=contentId,proto3" json:"contentId,omitempty"`
	TimeStamp []int64 `protobuf:"varint,3,rep,packed,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *PullResp) Reset() {
	*x = PullResp{}
	mi := &file_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResp) ProtoMessage() {}

func (x *PullResp) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResp.ProtoReflect.Descriptor instead.
func (*PullResp) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{2}
}

func (x *PullResp) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *PullResp) GetContentId() []int64 {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *PullResp) GetTimeStamp() []int64 {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type PullOutBoxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *PullOutBoxReq) Reset() {
	*x = PullOutBoxReq{}
	mi := &file_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullOutBoxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullOutBoxReq) ProtoMessage() {}

func (x *PullOutBoxReq) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullOutBoxReq.ProtoReflect.Descriptor instead.
func (*PullOutBoxReq) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{3}
}

func (x *PullOutBoxReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PullOutBoxReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PullOutBoxResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentId []int64 `protobuf:"varint,1,rep,packed,name=contentId,proto3" json:"contentId,omitempty"`
	TimeStamp []int64 `protobuf:"varint,2,rep,packed,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *PullOutBoxResp) Reset() {
	*x = PullOutBoxResp{}
	mi := &file_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullOutBoxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullOutBoxResp) ProtoMessage() {}

func (x *PullOutBoxResp) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullOutBoxResp.ProtoReflect.Descriptor instead.
func (*PullOutBoxResp) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{4}
}

func (x *PullOutBoxResp) GetContentId() []int64 {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *PullOutBoxResp) GetTimeStamp() []int64 {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

var File_feed_proto protoreflect.FileDescriptor

var file_feed_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x65,
	0x65, 0x64, 0x52, 0x70, 0x63, 0x22, 0x3d, 0x0a, 0x0d, 0x70, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x55, 0x0a, 0x07, 0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5e, 0x0a, 0x08, 0x70,
	0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3d, 0x0a, 0x0d, 0x70,
	0x75, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4c, 0x0a, 0x0e, 0x70, 0x75,
	0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x32, 0xb2, 0x01, 0x0a, 0x0b, 0x66, 0x65, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x70, 0x75, 0x6c, 0x6c,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x52, 0x70, 0x63,
	0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x66, 0x65, 0x65, 0x64, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2b, 0x0a, 0x04, 0x70, 0x75, 0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x66, 0x65, 0x65, 0x64,
	0x52, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x66, 0x65,
	0x65, 0x64, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d,
	0x0a, 0x0a, 0x70, 0x75, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x42, 0x6f, 0x78, 0x12, 0x16, 0x2e, 0x66,
	0x65, 0x65, 0x64, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x75, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x42, 0x6f,
	0x78, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x52, 0x70, 0x63, 0x2e, 0x70,
	0x75, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x52, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_feed_proto_rawDescOnce sync.Once
	file_feed_proto_rawDescData = file_feed_proto_rawDesc
)

func file_feed_proto_rawDescGZIP() []byte {
	file_feed_proto_rawDescOnce.Do(func() {
		file_feed_proto_rawDescData = protoimpl.X.CompressGZIP(file_feed_proto_rawDescData)
	})
	return file_feed_proto_rawDescData
}

var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_feed_proto_goTypes = []any{
	(*PullLatestReq)(nil),  // 0: feedRpc.pullLatestReq
	(*PullReq)(nil),        // 1: feedRpc.pullReq
	(*PullResp)(nil),       // 2: feedRpc.pullResp
	(*PullOutBoxReq)(nil),  // 3: feedRpc.pullOutBoxReq
	(*PullOutBoxResp)(nil), // 4: feedRpc.pullOutBoxResp
}
var file_feed_proto_depIdxs = []int32{
	0, // 0: feedRpc.feedService.pullLatest:input_type -> feedRpc.pullLatestReq
	1, // 1: feedRpc.feedService.pull:input_type -> feedRpc.pullReq
	3, // 2: feedRpc.feedService.pullOutBox:input_type -> feedRpc.pullOutBoxReq
	2, // 3: feedRpc.feedService.pullLatest:output_type -> feedRpc.pullResp
	2, // 4: feedRpc.feedService.pull:output_type -> feedRpc.pullResp
	4, // 5: feedRpc.feedService.pullOutBox:output_type -> feedRpc.pullOutBoxResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_rawDesc = nil
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
