// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: feed.proto

package server

import (
	"context"

	"bilibili/services/feed/internal/logic"
	"bilibili/services/feed/internal/svc"
	"bilibili/services/feed/proto/feedRpc"
)

type FeedServiceServer struct {
	svcCtx *svc.ServiceContext
	feedRpc.UnimplementedFeedServiceServer
}

func NewFeedServiceServer(svcCtx *svc.ServiceContext) *FeedServiceServer {
	return &FeedServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FeedServiceServer) PullLatest(ctx context.Context, in *feedRpc.PullLatestReq) (*feedRpc.PullResp, error) {
	l := logic.NewPullLatestLogic(ctx, s.svcCtx)
	return l.PullLatest(in)
}

func (s *FeedServiceServer) Pull(ctx context.Context, in *feedRpc.PullReq) (*feedRpc.PullResp, error) {
	l := logic.NewPullLogic(ctx, s.svcCtx)
	return l.Pull(in)
}
