// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: auth.proto

package server

import (
	"context"

	"auth/internal/logic"
	"auth/internal/svc"
	"auth/proto/AuthRpc"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	AuthRpc.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) Authentication(ctx context.Context, in *AuthRpc.AuthenticationReq) (*AuthRpc.AuthenticationResp, error) {
	l := logic.NewAuthenticationLogic(ctx, s.svcCtx)
	return l.Authentication(in)
}

func (s *AuthServiceServer) Refresh(ctx context.Context, in *AuthRpc.RefreshReq) (*AuthRpc.RefreshResp, error) {
	l := logic.NewRefreshLogic(ctx, s.svcCtx)
	return l.Refresh(in)
}

func (s *AuthServiceServer) Create(ctx context.Context, in *AuthRpc.CreateReq) (*AuthRpc.CreateResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}
