// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc1
// source: in.proto

package InnerGetWay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     []int64 `protobuf:"varint,1,rep,packed,name=UserId,proto3" json:"UserId,omitempty"`
	PayLoad    string  `protobuf:"bytes,2,opt,name=PayLoad,proto3" json:"PayLoad,omitempty"`
	EncodeType string  `protobuf:"bytes,3,opt,name=EncodeType,proto3" json:"EncodeType,omitempty"`
	Global     bool    `protobuf:"varint,4,opt,name=Global,proto3" json:"Global,omitempty"`
}

func (x *PushMessageReq) Reset() {
	*x = PushMessageReq{}
	mi := &file_in_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageReq) ProtoMessage() {}

func (x *PushMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_in_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageReq.ProtoReflect.Descriptor instead.
func (*PushMessageReq) Descriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessageReq) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *PushMessageReq) GetPayLoad() string {
	if x != nil {
		return x.PayLoad
	}
	return ""
}

func (x *PushMessageReq) GetEncodeType() string {
	if x != nil {
		return x.EncodeType
	}
	return ""
}

func (x *PushMessageReq) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

type PushMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushMessageResp) Reset() {
	*x = PushMessageResp{}
	mi := &file_in_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResp) ProtoMessage() {}

func (x *PushMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_in_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResp.ProtoReflect.Descriptor instead.
func (*PushMessageResp) Descriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{1}
}

var File_in_proto protoreflect.FileDescriptor

var file_in_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x57, 0x61, 0x79, 0x22, 0x7a, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x4c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0x5e, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b,
	0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x49, 0x6e,
	0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x57, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x57, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x57, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_in_proto_rawDescOnce sync.Once
	file_in_proto_rawDescData = file_in_proto_rawDesc
)

func file_in_proto_rawDescGZIP() []byte {
	file_in_proto_rawDescOnce.Do(func() {
		file_in_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_proto_rawDescData)
	})
	return file_in_proto_rawDescData
}

var file_in_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_in_proto_goTypes = []any{
	(*PushMessageReq)(nil),  // 0: InnerGetWay.PushMessageReq
	(*PushMessageResp)(nil), // 1: InnerGetWay.PushMessageResp
}
var file_in_proto_depIdxs = []int32{
	0, // 0: InnerGetWay.PushMessageService.PushMessage:input_type -> InnerGetWay.PushMessageReq
	1, // 1: InnerGetWay.PushMessageService.PushMessage:output_type -> InnerGetWay.PushMessageResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_in_proto_init() }
func file_in_proto_init() {
	if File_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_in_proto_goTypes,
		DependencyIndexes: file_in_proto_depIdxs,
		MessageInfos:      file_in_proto_msgTypes,
	}.Build()
	File_in_proto = out.File
	file_in_proto_rawDesc = nil
	file_in_proto_goTypes = nil
	file_in_proto_depIdxs = nil
}
