// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: content.proto

package server

import (
	"context"

	"bilibili/services/content/internal/logic"
	"bilibili/services/content/internal/svc"
	"bilibili/services/content/proto/contentRpc"
)

type ContentServiceServer struct {
	svcCtx *svc.ServiceContext
	contentRpc.UnimplementedContentServiceServer
}

func NewContentServiceServer(svcCtx *svc.ServiceContext) *ContentServiceServer {
	return &ContentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentServiceServer) Publish(ctx context.Context, in *contentRpc.PublishReq) (*contentRpc.Empty, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}
