// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: in.proto

package server

import (
	"context"

	"puhser/getway/in/internal/logic"
	"puhser/getway/in/internal/svc"
	"puhser/getway/in/proto/InnerGetWay"
)

type PushMessageServiceServer struct {
	svcCtx *svc.ServiceContext
	InnerGetWay.UnimplementedPushMessageServiceServer
}

func NewPushMessageServiceServer(svcCtx *svc.ServiceContext) *PushMessageServiceServer {
	return &PushMessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PushMessageServiceServer) PushMessage(ctx context.Context, in *InnerGetWay.PushMessageReq) (*InnerGetWay.PushMessageResp, error) {
	l := logic.NewPushMessageLogic(ctx, s.svcCtx)
	return l.PushMessage(in)
}
